### ISSUE TITLE
Using a file on another filesystem results in a permission error, and the resulting file isn't trimmed

### ISSUE THREAD

**Issue by n3mur1t0r** [AnalogMan151/XCI_Trimmer#1]
Hello,

I tried using the script in Ubuntu 18.04. The script was saved in the home directory of the current user, while the XCI file was on a samba mounted share, mounted using the uid and gid of the current user.

This is the error:
```
Traceback (most recent call last):
  File "XCI_Trimmer.py", line 168, in <module>
    main()
  File "XCI_Trimmer.py", line 161, in main
    trim()
  File "XCI_Trimmer.py", line 82, in trim
    copy2(filename, copypath, follow_symlinks=False)
  File "/usr/lib/python3.5/shutil.py", line 252, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 197, in copystat
    lookup("chmod")(dst, mode, follow_symlinks=follow)
PermissionError: [Errno 13] Permission denied: 'filename_trimmed.xci'
```

So, I tried using copy instead of copy2. Then, this is the error:
```
Traceback (most recent call last):
  File "XCI_Trimmer.py", line 168, in <module>
    main()
  File "XCI_Trimmer.py", line 161, in main
    trim()
  File "XCI_Trimmer.py", line 82, in trim
    copy(filename, copypath)
  File "/usr/lib/python3.5/shutil.py", line 236, in copy
    copymode(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 138, in copymode
    chmod_func(dst, stat.S_IMODE(st.st_mode))
PermissionError: [Errno 13] Permission denied: 'filename_trimmed.xci'
```

In both cases, the 'filename_trimmed.xci' file gets created, but it doesn't get trimmed (obviously, as it throws that error and doesn't execute what comes next). Also, I receive these errors on a FreeNAS 11.1 system, with the XCI file residing on the local ZFS volume.

I found two ways of making it work:

1) I copied the XCI file to the local Linux filesystem, i.e. in the home directory of the current user, then ran the script. This is not ideal, as I'd like to create the trimmed files in the same location as the original ones.

2) Instead of copy2 and copy, I used copyfile. As per the documentation, this procedure copies the file without copying the permission mode and metadata. This is not a big deal, since the date of the trimmed file gets changed anyway when it's trimmed.

Therefore, I see no reason to use copy2 instead of copyfile. But then again, I'm not a Python developer, but I am trying to learn.

Anyway, if you agree, please let me know and I will submit a pull request. Otherwise, I'd really like to know why should we use copy2 instead of copyfile.

Thanks and sorry for the wall of text!

**Comment by AnalogMan151** [comment]
copy2 was used simply because I did want to preserve permissions and metadata, but honestly that was just me being precautions. I don't actually see a need for keeping the permissions or metadata and if it's causing issues, go right ahead and submit the pull.
